// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkqtwkaeaoagkvszpgce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrcXR3a2FlYW9hZ2t2c3pwZ2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTc0OTYsImV4cCI6MjA3MDMzMzQ5Nn0.KfKrpzoJc785vusa-a5BmRgvthEZAXT5Uig7oAmk1Jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});